spring:
  thymeleaf:
    cache: false
    enabled: true
    encoding: UTF-8
    mode: HTML5
    prefix: classpath:/templates/
    suffix: .html
    servlet:
      content-type: text/html
  datasource:
    url: jdbc:mysql://localhost:3306/miaosha?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    username: root
    password: ntech
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      filters: stat
      max-active: 1000
      initial-size: 100
      max-wait: 60000
      min-idle: 500
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 30000
      validation-query: select 'x'
      test-while-idle: true
      test-on-return: false
      test-on-borrow: false
  resources:
    add-mappings: true
    cache:
      period: 3600s
    chain:
      cache: true
      enabled: true
      compressed: true
      html-application-cache: true
    static-locations: classpath:/static/
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    listener:
      simple:
        # 消费者数量
        concurrency: 10
        max-concurrency: 10
        # 消费者每次取的数量
        prefetch: 1
        auto-startup: true
        # 消费失败后重试
        default-requeue-rejected: true
        retry:
          # 启动重试
          enabled: true
          # 1s重试一次
          initial-interval: 1000s
          # 最大重试三次
          max-attempts: 3
          # 最大间隔10s
          max-interval: 10000s
          # 上一次等待时间 * multiplier = 下一次重试的时间. (0 < 下次重试时间 <= max-interval)
          multiplier: 1.0
mybatis:
  mapper-locations: classpath:/mapper/*Mapper.xml
  type-aliases-package: top.imyzt.study.miaosha.domain
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 3000
redis:
  host: localhost
  port: 6379
  database: 0
  timeout: 10000
  password:
  pool-max-total: 1000
  pool-max-idle: 500
  pool-max-wait: 500
